import { logoCompany01Upwork, logoCompany02Trello, logoCompany03Zoom, logoCompany04Zapier } from "../../public/imgassets/assets-img";

import * as logos from '../../public/imgassets/company/asset-img-company'; // Assuming your previous exports are here

const testimonialsList2 = [
    {
        id: "ActiveCampaign",
        logoSrc: logos.activecampaign,
        company: "ActiveCampaign",
        name: "Marcus Aurelius",
        title: "Marketing Director",
        comment: "The automation workflows integrated into the frontend are seamless. A true master of React and logic.",
        stars: 5,
    },
    {
        id: "Adobe",
        logoSrc: logos.adobe,
        company: "Adobe",
        name: "Lydia Vance",
        title: "Creative Director",
        comment: "Precision is hard to find, but this developer hits every pixel-perfect requirement we throw at them.",
        stars: 5,
    },
    {
        id: "Airtable",
        logoSrc: logos.airtable,
        company: "Airtable",
        name: "Julian Chen",
        title: "Operations Lead",
        comment: "Transformed our complex data structures into a beautiful, easy-to-use dashboard. Simply brilliant.",
        stars: 4,
    },
    {
        id: "Airwallex",
        logoSrc: logos.airwallex,
        company: "Airwallex",
        name: "Sophie Zhang",
        title: "Product Manager",
        comment: "Excellent handling of financial data visualization. The performance optimizations were exactly what we needed.",
        stars: 5,
    },
    {
        id: "Amplitude",
        logoSrc: logos.amplitude,
        company: "Amplitude",
        name: "Derek Foster",
        title: "Data Scientist",
        comment: "A developer who actually understands analytics. The implementation was clean and the tracking is flawless.",
        stars: 5,
    },
    {
        id: "Attentive",
        logoSrc: logos.attentive,
        company: "Attentive",
        name: "Riley Cooper",
        title: "VP of Engineering",
        comment: "The mobile-first approach taken on our latest campaign site was executed to perfection. Great communication.",
        stars: 4,
    },
    {
        id: "Automattic",
        logoSrc: logos.automattic,
        company: "Automattic",
        name: "Helena Hills",
        title: "Open Source Contributor",
        comment: "Clean, maintainable code that follows all best practices. It's rare to find someone this disciplined.",
        stars: 5,
    },
    {
        id: "Braze",
        logoSrc: logos.braze,
        company: "Braze",
        name: "Arthur Morgan",
        title: "CRM Specialist",
        comment: "The dynamic components created for our messaging platform are robust and very easy to scale.",
        stars: 5,
    },
    {
        id: "BrowserStack",
        logoSrc: logos.browserstack,
        company: "BrowserStack",
        name: "Clara Oswald",
        title: "QA Lead",
        comment: "I've never seen code come through with so few cross-browser issues. High attention to detail.",
        stars: 5,
    },
    {
        id: "Calendly",
        logoSrc: logos.calendly,
        company: "Calendly",
        name: "James Wilson",
        title: "UX Researcher",
        comment: "The scheduling interface is buttery smooth. User feedback on the new UI has been overwhelmingly positive.",
        stars: 5,
    },
    {
        id: "Carta",
        logoSrc: logos.carta,
        company: "Carta",
        name: "Elena Rodriguez",
        title: "Chief of Staff",
        comment: "Professional, timely, and technically gifted. Handled our equity management dashboard with ease.",
        stars: 4,
    },
    {
        id: "Contentful",
        logoSrc: logos.contentful,
        company: "Contentful",
        name: "Simon Peter",
        title: "Head of Content",
        comment: "The headless CMS integration was flawless. Our content team can now work faster than ever before.",
        stars: 5,
    },
    {
        id: "CultureAmp",
        logoSrc: logos.cultureamp,
        company: "Culture Amp",
        name: "Anita Borg",
        title: "People Scientist",
        comment: "Beautifully crafted survey interfaces that encourage engagement. A pleasure to work with.",
        stars: 5,
    },
    {
        id: "Databricks",
        logoSrc: logos.databricks,
        company: "Databricks",
        name: "Kevin Flynn",
        title: "Solutions Architect",
        comment: "Managed to make high-density data look elegant. The performance on large datasets is impressive.",
        stars: 5,
    },
    {
        id: "Elastic",
        logoSrc: logos.elastic,
        company: "Elastic",
        name: "Sarah Connor",
        title: "Search Engineer",
        comment: "The search UI implementation is lightning fast. Highly intuitive and very well structured.",
        stars: 5,
    },
    {
        id: "Fivetran",
        logoSrc: logos.fivetran,
        company: "Fivetran",
        name: "George Boole",
        title: "Data Engineer",
        comment: "Strong technical foundation and great problem-solving skills. Delivered ahead of schedule.",
        stars: 4,
    },
    {
        id: "Freshworks",
        logoSrc: logos.freshworks,
        company: "Freshworks",
        name: "Maya Angelou",
        title: "Customer Success",
        comment: "The support portal redesign significantly reduced our bounce rate. Exceptional design sense.",
        stars: 5,
    },
    {
        id: "GitHub",
        logoSrc: logos.github,
        company: "GitHub",
        name: "Linus Torvalds",
        title: "Maintainer",
        comment: "Impressive PR quality. Every component is modular, tested, and easy to review.",
        stars: 5,
    },
    {
        id: "Gitlab",
        logoSrc: logos.gitlab,
        company: "Gitlab",
        name: "Syd Barrett",
        title: "DevOps Lead",
        comment: "Exceptional work on the CI/CD dashboard. The real-time updates are handled perfectly.",
        stars: 5,
    },
    {
        id: "Gong",
        logoSrc: logos.gong,
        company: "Gong",
        name: "Victor Hugo",
        title: "Sales Enablement",
        comment: "Translated complex audio insights into a very readable and actionable frontend. Highly recommended.",
        stars: 4,
    },
    {
        id: "Grammarly",
        logoSrc: logos.grammarly,
        company: "Grammarly",
        name: "Jane Austen",
        title: "Editor in Chief",
        comment: "The text-editor integration is flawless. Zero lag and perfectly responsive across all devices.",
        stars: 5,
    },
    {
        id: "Gusto",
        logoSrc: logos.gusto,
        company: "Gusto",
        name: "Adam Smith",
        title: "Payroll Manager",
        comment: "Navigating complex tax forms is now a breeze thanks to the intuitive UI flow created here.",
        stars: 5,
    },
    {
        id: "HashiCorp",
        logoSrc: logos.hashicorp,
        company: "HashiCorp",
        name: "Ada Lovelace",
        title: "Infrastructure Engineer",
        comment: "Excellent use of modern CSS and animations. The cloud console feels futuristic and snappy.",
        stars: 5,
    },
    {
        id: "Hopin",
        logoSrc: logos.hopin,
        company: "Hopin",
        name: "Elon Tusk",
        title: "Event Coordinator",
        comment: "Handled the high-traffic demands of our virtual event platform without a single glitch.",
        stars: 4,
    },
    {
        id: "InVision",
        logoSrc: logos.invision,
        company: "InVision",
        name: "Pablo Picasso",
        title: "Design Lead",
        comment: "It's rare to find a developer who understands design as deeply as they understand code. Perfection.",
        stars: 5,
    },
    {
        id: "LaunchDarkly",
        logoSrc: logos.launchdarkly,
        company: "LaunchDarkly",
        name: "Grace Hopper",
        title: "Feature Lead",
        comment: "The toggle-management UI is incredibly clean. A masterclass in React state management.",
        stars: 5,
    },
    {
        id: "Loom",
        logoSrc: logos.loom,
        company: "Loom",
        name: "Reed Hastings",
        title: "Video Engineer",
        comment: "Optimized our video player for low-bandwidth users while keeping the UI beautiful. Great job.",
        stars: 5,
    },
    {
        id: "Mailchimp",
        logoSrc: logos.mailchimp,
        company: "Mailchimp",
        name: "Freddie Mercury",
        title: "Email Marketer",
        comment: "The template builder is now 2x faster. The code quality is as high as the performance gains.",
        stars: 5,
    },
    {
        id: "Miro",
        logoSrc: logos.miro,
        company: "Miro",
        name: "Leonardo Da Vinci",
        title: "Collaboration Lead",
        comment: "Exceptional work on the infinite canvas component. The zooming and panning feel natural.",
        stars: 5,
    },
    {
        id: "Notion",
        logoSrc: logos.notion,
        company: "Notion",
        name: "Marie Curie",
        title: "Product Designer",
        comment: "Clean, minimal, and functional. Exactly the aesthetic we strive for. A fantastic collaborator.",
        stars: 5,
    },
    {
        id: "Opendoor",
        logoSrc: logos.opendoor,
        company: "Opendoor",
        name: "Frank Lloyd Wright",
        title: "Real Estate Analyst",
        comment: "The map integration and property listing flow are world-class. User conversion has increased.",
        stars: 4,
    },
    {
        id: "Outreach",
        logoSrc: logos.outreach,
        company: "Outreach",
        name: "Zig Ziglar",
        title: "Sales Director",
        comment: "The sequence builder UI is incredibly intuitive. It has changed the way our team works.",
        stars: 5,
    },
    {
        id: "Pendo",
        logoSrc: logos.pendo,
        company: "Pendo",
        name: "Alan Turing",
        title: "Product Analyst",
        comment: "Integrated complex user-guide overlays with zero impact on main thread performance. Impressive.",
        stars: 5,
    },
    {
        id: "Pipedrive",
        logoSrc: logos.pipedrive,
        company: "Pipedrive",
        name: "Dale Carnegie",
        title: "Account Executive",
        comment: "The drag-and-drop deal board is fantastic. Very responsive and handles state perfectly.",
        stars: 5,
    },
    {
        id: "Plaid",
        logoSrc: logos.plaid,
        company: "Plaid",
        name: "John Maynard Keynes",
        title: "Fintech Lead",
        comment: "Secure, fast, and reliable frontend work. Handled our sensitive authentication flows with care.",
        stars: 5,
    },
    {
        id: "Postman",
        logoSrc: logos.postman,
        company: "Postman",
        name: "Katherine Johnson",
        title: "API Architect",
        comment: "Building a complex API client in the browser is no small feat. This developer nailed it.",
        stars: 4,
    },
    {
        id: "Razorpay",
        logoSrc: logos.razorpay,
        company: "Razorpay",
        name: "Srinivasa Ramanujan",
        title: "Payments Engineer",
        comment: "The checkout experience is flawless. High conversion rates and zero friction. Exceptional work.",
        stars: 5,
    },
    {
        id: "Slack",
        logoSrc: logos.slack,
        company: "Slack",
        name: "Stewart Butterfield",
        title: "CTO",
        comment: "Exceptional attention to detail in the sidebar and navigation transitions. Makes the app feel alive.",
        stars: 5,
    },
    {
        id: "Webflow",
        logoSrc: logos.webflow,
        company: "Webflow",
        name: "Hedy Lamarr",
        title: "No-Code Expert",
        comment: "Even in a no-code company, we appreciate high-quality custom React components. Superb quality.",
        stars: 5,
    },
    {
        id: "Zapier",
        logoSrc: logos.zapier,
        company: "Zapier",
        name: "Nikola Tesla",
        title: "Automation Engineer",
        comment: "The logic used to connect various API endpoints into the frontend UI is elegant and robust.",
        stars: 5,
    },
];

const testimonialsList1 = [
    {
        id: "Upwork",
        logoSrc: logoCompany01Upwork,
        company: "Upwork",
        name: "Thom Haye",
        title: "Project Manager",
        comment: "Highly skilled frontend developer with an eye for design. Transformed our wireframes into a seamless and responsive web experience. Highly recommended!",
        stars: 5,
    }, {
        id: "Trello",
        logoSrc: logoCompany02Trello,
        company: "Trello",
        name: "Emily Carter",
        title: "Head of Product",
        comment: "An absolute pleasure to work with! Delivered a stunning, high-performance website that exceeded expectations. Attention to detail and problem-solving skills are top-notch!",
        stars: 5,
    }, {
        id: "Zoom",
        logoSrc: logoCompany03Zoom,
        company: "Zoom",
        name: "Michael Brown",
        title: "Lead Developer",
        comment: "A pleasure to collaborate with! Writes clean, maintainable code while effectively working with designers and backend engineers. Outstanding work!",
        stars: 5,
    }, {
        id: "Zappier",
        logoSrc: logoCompany04Zapier,
        company: "Zappier",
        name: "Sarah Lee",
        title: "Engineering Manager",
        comment: "An exceptional frontend developer with a deep understanding of UI/UX principles. The ability to translate design into pixel-perfect code is truly impressive. A valuable asset to any team!",
        stars: 5,
    },
];

export const allTestimonials = [...testimonialsList1, ...testimonialsList2];